### ISSUE TITLE
Biblioteca cvui para criação de GUI em OpenCV

### ISSUE THREAD

**Issue by Dovyski** [UFFSCV/dojo_uffscv#1]
Olá! Vocês já deram uma olhada na [cvui](https://dovyski.github.io/cvui/) para criação de interfaces gráficas para apliações OpenCV (Python e C++)? Eu sou o autor dessa biblioteca (publicidade gratuita sem remorso algum 😛), então eu poderia fazer uma aula/demonstração sobre ela se for do interesse de vocês.

**Comment by UFFSCV** [comment]
Olá! @Dovyski, podemos usar essa biblioteca sim! E seria muito massa ter um dojo feito por ti!

**Comment by Dovyski** [comment]
Excelente! Onde eu posso consultar a agenda dos encontros de vocês?

**Comment by UFFSCV** [comment]
Nossa agenda deste semestre pode ser consultada neste [aqui](https://docs.google.com/spreadsheets/d/1XEvg_1SNOjQ_5RnXh3HMgUoVh3qJYcy4OsndaMje5Dw/edit?usp=sharing) as atividades que estão marcadas como não confirmadas é pq ainda não há certeza de ser ocorrida ou pode ser substituída por outra, no caso, pelo seu dojo

**Comment by Dovyski** [comment]
Eu poderia fazer o dojo no dia 13/06, que tal?

**Comment by UFFSCV** [comment]
Pode sim, agendado então!

**Comment by Dovyski** [comment]
Ótimo! Que horas e em qual local?

**Comment by UFFSCV** [comment]
às 19h no LAB 405B

**Comment by Dovyski** [comment]
Pessoal, eu marquei o dojo na minha agenda na quinta da semana que vem, e não na quinta de hoje :(
